main_node:
  ros__parameters:
    # Robot parameters
    robot_name: "jackal_ugv"
    max_lin_vel: 0.4
    min_lin_vel: 0.0
    max_ang_vel: 1.5
    min_ang_vel: -1.5
    robot_type: "rectangular" # rectangular or circular
    robot_radius: 0.2 # [m], If robot_type is cicrular
    robot_size: [0.508, 0.430] # [m, m], Length, Width if robot_type is rectangular
    collision_tolerance: 0.05 # [m], tollerance of collision added to robot_radius or robot_size
    warning_tolerance: 0.1 # [m], warning window added to robot_radius or robot_size
    goal_tolerance: 0.40

    # World parameters
    world_name: "new_indoor.world" #Leave empty to obtain no world
    data_path: "new_indoor.json"

    # Task parameters
    task: 'goToPose' # goToPose, Following, Vineyards
    
    # Sensors parameters
    sensor: 'lidar' # lidar or rgb_camera or depth_camera
    visual_data: 'features'
    features: 12544
    channels: 1
    imu_enabled: "false"
    camera_enabled: "false"
    stereo_camera_enabled: "true"
    lidar_enabled: "true"
    tracking_enabled: "true" # DIANA's Track Stack
    sensors_topic:
      rgb_topic: "/camera/image_raw"
      depth_topic: "/camera/depth/image_raw"
      laser_topic: "/scan"
      imu_topic: "/imu/data"
      odom_topic: "/odom"
    laser_param:
      max_distance: 12.0 # Meters
      num_points: 36 # int divider of 360
    depth_param:
      dist_cutoff: 7 # Meters
      width: 112 # Used for resizing the image
      height: 112 # Used for resizing the image
      show_image: False
    rgb_param:
      width: 640
      height: 480
      show_image: False 
